console.log("=============isArray=====================");

const hobbies=["sleeping","dance","sing","playing","roaming"];
const isArrayOrNot=Array.isArray(hobbies);
console.log("hobbies array or not=",isArrayOrNot);
console.log("==================================");
const cars=["swift","ritz","creta","i20","datsson"];
const isArrayOrNot1=Array.isArray(cars);
console.log("cars array or not=",isArrayOrNot1);
console.log("==================================");
const mobiles=['samsung','vivo','redme','iphone'];
const isArrayOrNot2=Array.isArray(mobiles);
console.log("mobiles array or not=",isArrayOrNot2);
console.log("==================================");
const laptops=['lenovo','','asus','dell',1,"-----"];
const isArrayOrNot3=Array.isArray(laptops);
console.log("laptops array or not=",isArrayOrNot3);
console.log("==================================");
const vegetables=['brinjol','cucumber','carrot','tomato'];
const isArrayOrNot4=Array.isArray(vegetables);
console.log("vegetables array or not=",isArrayOrNot4);
console.log("==================================");
const arr=({foo: 123});
const isArrayOrNot5=Array.isArray(arr);
console.log("arr array or not=",isArrayOrNot5);
console.log("=========================");
const channels=['zee','ndtv','cn','pogo'];
const isArrayOrNot6=Array.isArray(channels);
console.log("channels array or not=",isArrayOrNot6);
console.log("==================================");
const arr1=( 123);
const isArrayOrNot7=Array.isArray(arr1);
console.log("arr1 array or not=",isArrayOrNot7);
console.log("=========================");
const arr2=( 123 ,456,789);
const isArrayOrNot8=Array.isArray(arr2);
console.log("arr2 array or not=",isArrayOrNot8);
console.log("=========================");
const animals=['monkey','cat','dog','pig'];
const isArrayOrNot9=Array.isArray(animals);
console.log("animals array or not=",isArrayOrNot9);
console.log("==================================");
console.log("===============incudemethod===========")
const hobbies0=["sleeping","dance","sing","playing","roaming"];
const hasDance=hobbies.includes("dance");
console.log("using includes method",hasDance);
console.log("===========================");
const hobbies1=["sleeping","dance","sing","playing","roaming"];
const hascooking=hobbies1.includes("cooking");
console.log("using includes method",hascooking);
console.log("===========================");
const hobbies2=["sleeping","dance","sing","playing","roaming"];
const hassing=hobbies2.includes("sing");
console.log("using includes method",hassing);
console.log("===========================");
const hobbies3=["sleeping","dance","sing","playing","roaming"];
const hassleeping=hobbies3.includes("sleeping");
console.log("using includes method",hassleeping);
console.log("===========================");
const hobbies4=["sleeping","dance","sing","playing","roaming"];
const hasPubg=hobbies4.includes("Pubg");
console.log("using includes method",hasPubg);
console.log("===========================");
const hobbies5=["sleeping","dance","sing","playing","roaming"];
const hasplaying=hobbies5.includes("playing");
console.log("using includes method",hasplaying);
console.log("===========================");
const animalss=['monkey','cat','dog','pig'];
const hasmonkey=animals.includes("monkey");
console.log("using includes method",hasmonkey);
console.log("===========================");
const animals1=['monkey','cat','dog','pig'];
const hasdonkey=animals1.includes("donkey");
console.log("using includes method",hasdonkey);
console.log("===========================");
const animals2=['monkey','cat','dog','pig'];
const hasgorilla=animals2.includes("gorilla");
console.log("using includes method",hasgorilla);
console.log("===========================");
const animals3=['monkey','cat','dog','pig'];
const hascat=animals3.includes("cat");
console.log("using includes method",hascat);
console.log("===========================");
const animals4=['monkey','cat','dog','pig'];
const hasdog=animals4.includes("dog");
console.log("using includes method",hasdog);
console.log("===========================");
console.log("=================pop method=============");
const hobbiess=["sleeping","dance","sing","playing","roaming"];

hobbies.pop();
console.log("after pop method",hobbies);
console.log("=========================");
hobbies.pop();
console.log("after pop method",hobbies);
console.log("=========================");
hobbies.pop();
console.log("after pop method",hobbies);
console.log("=========================");
hobbies.pop();
console.log("after pop method",hobbies);
console.log("=========================");
hobbies.pop();
console.log("after pop method",hobbies);
console.log("=========================");
const birds=['parrot','crow','pigeon','duck'];
birds.pop();
console.log("after pop method",birds);
console.log("==============================");
birds.pop();
console.log("after pop method",birds);
console.log("==============================");
birds.pop();
console.log("after pop method",birds);
console.log("==============================");
birds.pop();
console.log("after pop method",birds);
console.log("==============================");
const animals99=['monkey','cat','dog','pig'];
animals.pop();
console.log("after pop method",animals);
console.log("================================");
console.log("===================push method==================")
const hobbies99=["sleeping","dance","sing","playing","roaming"];
hobbies.push("guiter","volleyball");
console.log("after push method",hobbies);
console.log("===============================");
const hobbies10=["sleeping","dance","sing","playing","roaming"];
hobbies1.push("guiter");
console.log("after push method",hobbies1);
console.log("===============================");
const hobbies20=["sleeping","dance","sing","playing","roaming"];
hobbies2.push("pubg");
console.log("after push method",hobbies2);
console.log("===============================");
const hobbies30=["sleeping","dance","sing","playing","roaming"];
hobbies3.push("tv");
console.log("after push method",hobbies3);
console.log("===============================");
const hobbies40=["sleeping","dance","sing","playing","roaming"];
hobbies4.push("music");
console.log("after push method",hobbies4);
console.log("===============================");
const hobbies50=["sleeping","dance","sing","playing","roaming"];
hobbies5.push("stunts");
console.log("after push method",hobbies5);
console.log("===============================");
const hobbies6=["sleeping","dance","sing","playing","roaming"];
hobbies6.push("kabbadi");
console.log("after push method",hobbies6);
console.log("===============================");
const hobbies7=["sleeping","dance","sing","playing","roaming"];
hobbies7.push("khokho");
console.log("after push method",hobbies7);
console.log("===============================");
const hobbies8=["sleeping","dance","sing","playing","roaming"];
hobbies8.push("fasion design");
console.log("after push method",hobbies8);
console.log("===============================");
const hobbies9=["sleeping","dance","sing","playing","roaming"];
hobbies9.push("");
console.log("after push method",hobbies9);
console.log("===============================");
console.log("=====================Shiftarraymethod==========");
const hobbies00=["sleeping","dance","sing","playing","roaming"];
        
        hobbies.shift();
        console.log("after shift method",hobbies);
        console.log("=========================");
        hobbies.shift();
        console.log("after shift method",hobbies);
        console.log("=========================");
        hobbies.shift();
        console.log("after shift method",hobbies);
        console.log("=========================");
        hobbies.shift();
        console.log("after shift method",hobbies);
        console.log("=========================");
        hobbies.shift();
        console.log("after shift method",hobbies);
        console.log("=========================");
        const birds89=['parrot','crow','pigeon','duck'];
        birds.shift();
        console.log("after shift method",birds);
        console.log("==============================");
        birds.shift();
        console.log("after shift method",birds);
        console.log("==============================");
        birds.shift();
        console.log("after shift method",birds);
        console.log("==============================");
        birds.shift();
        console.log("after shift method",birds);
        console.log("==============================");
        const animals97=['monkey','cat','dog','pig'];
        animals.shift();
        console.log("after shift method",animals);
        console.log("==============================");
        console.log("=============splice slice joinmethod===========");
        hobbies1.splice(1,2,"bird watching","PUBG");
console.log("after splice method",hobbies1);
const afterSlice=hobbies1.slice(2,4);
console.log("After slice mehod ",hobbies1);
console.log("After slice method",afterSlice);

const indexOfCoding=hobbies1.indexOf("coding",1);
console.log("IndexOf Coding",indexOfCoding);
const stringHobbies=hobbies1.join("-");
 console.log("string of hobbies=",stringHobbies);
console.log("=====================================");
const hobbies23=["sleeping","cricket","eating","coding","roaming"];

hobbies2.splice(0,1,"hockey","stunts");
console.log("after splice method",hobbies2);
const afterSlice1=hobbies2.slice(2,4);
console.log("After slice mehod ",hobbies2);
console.log("After slice method",afterSlice1);

const indexOfeating=hobbies2.indexOf("eating",1);
console.log("IndexOf eating",indexOfeating);
const stringHobbies1=hobbies2.join("*");
 console.log("string of hobbies=",stringHobbies1);
console.log("=====================================");

const animals56=['monkey','cat','dog','pig'];


animals.splice(2,3,"donkey","camel");
console.log("after splice method",animals);
const afterSlice2=animals.slice(2,4);
console.log("After slice mehod ",animals);
console.log("After slice method",afterSlice2);

const indexOfcat=animals.indexOf("cat",1);
console.log("IndexOf cat",indexOfcat);
const stringHobbies2=animals.join("_");
 console.log("string of hobbies=",stringHobbies2);
console.log("=====================================");
const cloths=['jeans','tops','kurties','salvar'];

cloths.splice(1,2,"pant","shirt");
console.log("after splice method",cloths);
const afterSlice3=cloths.slice(2,4);
console.log("After slice mehod ",cloths);
console.log("After slice method",afterSlice3);

const indexOfjeans=cloths.indexOf("jeans",1);
console.log("IndexOf jeans",indexOfjeans);
console.log("================================");
const birds78=['parrot','crow','pigeon','duck'];
birds.splice(1,2,"crow","peacock");
console.log("after splice method",birds);
const afterSlice4=birds.slice(2,4);
console.log("After slice mehod ",birds);
console.log("After slice method",afterSlice4);

const indexOfpigeon=birds.indexOf("pigeon",0);
console.log("IndexOf pigeon",indexOfpigeon);
console.log("================================");
const channels78=['zee','ndtv','cn','pogo'];
channels.splice(1,2,"colors","sony");
console.log("after splice method",channels);
console.log("================================");
const vegetable78s=['brinjol','cucumber','carrot','tomato'];
vegetables.splice(1,2,"onion","cabbage");
console.log("after splice method",vegetables);
const afterSlice5=vegetables.slice(2,4);
console.log("After slice mehod ",vegetables);
console.log("After slice method",afterSlice5);

const indexOfcarrot=vegetables.indexOf("carrot",1);
console.log("IndexOf carrot",indexOfcarrot);
const stringHobbies5=vegetables.join("_");
 console.log("string of vegetables=",stringHobbies5);
console.log("================================");
const laptops90=['lenovo','hp','asus','dell'];
laptops.splice(1,2,"acer","sony");
console.log("after splice method",laptops);
console.log("================================");
const mobiles80=['samsung','vivo','redme','iphone'];
mobiles.splice(1,2,"nokia","1+");
console.log("after splice method",mobiles);
console.log("================================");
var fruits=['apple','mango','papaya','banana'];
fruits.splice(1,2,"watermelon","pineapple");
console.log("after splice method",fruits);
console.log("================================");
console.log("=========unshift array===============");
const hobbies777=["sleeping","dance","sing","playing","roaming"];
        hobbies.unshift("numismatics","cooking");
console.log("after unshift",hobbies);
console.log("========================================");
const hobbies145=["sleeping","dance","sing","playing","roaming"];
hobbies1.unshift("guiter");
console.log("after unshift method",hobbies1);
console.log("===============================");
const hobbies289=["sleeping","dance","sing","playing","roaming"];
hobbies2.unshift("pubg");
console.log("after unshift method",hobbies2);
console.log("===============================");
const hobbies389=["sleeping","dance","sing","playing","roaming"];
hobbies3.unshift("tv");
console.log("after unshift method",hobbies3);
console.log("===============================");
const hobbies489=["sleeping","dance","sing","playing","roaming"];
hobbies4.unshift("music");
console.log("after unshift method",hobbies4);
console.log("===============================");
const hobbies589=["sleeping","dance","sing","playing","roaming"];
hobbies5.unshift("stunts");
console.log("after unshift method",hobbies5);
console.log("===============================");
const hobbies609=["sleeping","dance","sing","playing","roaming"];
hobbies6.unshift("kabbadi");
console.log("after unshift method",hobbies6);
console.log("===============================");
const hobbies907=["sleeping","dance","sing","playing","roaming"];
hobbies7.unshift("khokho");
console.log("after unshift method",hobbies7);
console.log("===============================");
const hobbies008=["sleeping","dance","sing","playing","roaming"];
hobbies8.unshift("fasion design");
console.log("after unshift method",hobbies8);
console.log("===============================");
const hobbies009=["sleeping","dance","sing","playing","roaming"];
hobbies9.unshift("");
console.log("after unshift method",hobbies9);
console.log("===============================");